GET http://localhost:5000/users

###
GET http://localhost:5000/users/62c9c14343960657afe1207f

###
POST http://localhost:5000/users/
Content-Type: application/json

{
    "name": "Mutiasang",
    "email": "mutis@gmail.com",
    "gender": "Female"
}

###
PATCH http://localhost:5000/users/62c9c31dff13bd8d84dcb52a
Content-Type: application/json

{
    "name": "Mutias",
    "email": "mutis@gmail.com",
    "gender": "Female"
}